apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: hello-pod
spec:
  replicas: 2
  template: jenkins-slave2
    metadata:
      labels: jenkins-slave2
        app: webservers
    spec:
      containers:
        - name: jenkins-slave2
          image:https://cloud.docker.com/repository/docker/deepk/assign2:1.2
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000

      
